version: '3.7'

services:
  etcd0:
    image: quay.io/coreos/etcd:v3.3.25
    command:
      - /usr/local/bin/etcd
      -  --name
      - etcd0
      - --data-dir
      - /etcd-data
      - --advertise-client-urls
      - http://etcd0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      -  --initial-advertise-peer-urls
      - http://etcd0:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --initial-cluster
      - etcd0=http://etcd0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
  etcd1:
    image: quay.io/coreos/etcd:v3.3.25
    command:
      - /usr/local/bin/etcd
      -  --name
      - etcd0
      - --data-dir
      - /etcd-data
      - --advertise-client-urls
      - http://etcd0:2381
      - --listen-client-urls
      - http://0.0.0.0:2381
      -  --initial-advertise-peer-urls
      - http://etcd0:2382
      - --listen-peer-urls
      - http://0.0.0.0:2382
      - --initial-cluster
      - etcd0=http://etcd0:2382
    ports:
      - "2381:2381"
      - "2382:2382"
