# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
name: Node.js CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker-compose -f tools/docker/docker-compose.yml --project-directory ./ up -d
    - run: yarn install --frozen-lockfile
    - run: ./third_party/wait-for-it.sh 0.0.0.0:2379
    - run: ./third_party/wait-for-it.sh 0.0.0.0:2381
    - run: yarn test
