name: publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup etcd
        run: |
          docker-compose -f tools/docker/docker-compose.yml --project-directory ./ up -d
          ./third_party/wait-for-it.sh 0.0.0.0:2379
          ./third_party/wait-for-it.sh 0.0.0.0:2381
      - name: Run e2e tests
        run: |
          yarn install --frozen-lockfile
          yarn test
      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: build-dist
          path: dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v2
        with:
          name: build-dist
          path: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
